# Generated by Django 5.0.2 on 2024-04-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment',
            field=models.TextField(choices=[('C', 'Cash'), ('U', 'UPI'), ('O', 'Other'), ('Not Paid', 'N')], default='C'),
        ),
    ]
