# Generated by Django 5.0.2 on 2024-04-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_appointment_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='shift',
        ),
        migrations.AddField(
            model_name='doctor',
            name='shift',
            field=models.ManyToManyField(blank=True, null=True, to='main.shift'),
        ),
    ]
