# Generated by Django 5.0.2 on 2024-04-19 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.doctor'),
            preserve_default=False,
        ),
    ]
