# Generated by Django 5.0.2 on 2024-04-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_token_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='token_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
