# Generated by Django 5.0.2 on 2024-04-24 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_appointment_token_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Appointment', models.BooleanField(default=False)),
                ('OPD', models.BooleanField(default=False)),
                ('added_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('percentage', models.IntegerField()),
                ('added_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('added_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChargeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('added_date_time', models.DateTimeField(auto_now_add=True)),
                ('ChargeType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chargetype')),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('charge', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('added_date_time', models.DateTimeField(auto_now_add=True)),
                ('ChargeCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chargecategory')),
                ('ChargeType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chargetype')),
                ('TaxCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.taxcategory')),
                ('UnitType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.unittype')),
            ],
        ),
    ]
