# Generated by Django 5.0.2 on 2024-05-06 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_chargetype_taxcategory_unittype_chargecategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('nav_color', models.CharField(blank=True, max_length=30, null=True)),
                ('nav_text_color', models.CharField(blank=True, max_length=30, null=True)),
                ('btn_color', models.CharField(blank=True, max_length=30, null=True)),
                ('btn_text_color', models.CharField(blank=True, max_length=30, null=True)),
                ('body_color', models.CharField(blank=True, max_length=30, null=True)),
                ('body_text_color', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(blank=True, max_length=200, null=True)),
                ('hospital_code', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hospital_logo', models.ImageField(upload_to='media/')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.theme')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
