# Generated by Django 5.0.2 on 2024-05-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_theme_generalsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointed_time',
            field=models.TimeField(default='15:05:23'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointed_date',
            field=models.DateField(),
        ),
    ]
