# Generated by Django 5.0.2 on 2024-05-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_appointment_appointed_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='purpose',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='Purpose',
        ),
    ]
