# Generated by Django 5.0.2 on 2024-05-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_doctor_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='appointment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='front_office',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='staffs',
            field=models.BooleanField(default=False),
        ),
    ]
